#
# Copyright (C) 2023 Renesas Electronics Corporation.
# Copyright (C) 2023 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: aos_core_zephyr

  remotes:
    - name: xen-troops
      url-base: https://github.com/xen-troops

    - name: aoscloud
      url-base: https://github.com/aoscloud

    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

    - name: amoi
      url-base: https://github.com/oleksiimoisieiev/

    - name: dsemenets
      url-base: https://github.com/dsemenets/
  projects:
    - name: zephyr
      remote: dsemenets
      revision: xtop
      west-commands: scripts/west-commands.yml

    - name: aos_core_lib_cpp
      remote: aoscloud
      revision: 7cdf7299ff704c6046c1d49eb20070b08f171912

    - name: zephyr-xenlib
      remote: dsemenets
      revision: xentop

    - name: littlefs
      remote: zephyr
      path: modules/fs/littlefs
      groups:
        - fs
      revision: ca583fd297ceb48bced3c2548600dc615d67af24
